/*
* HTTP Cloud Function.
*
* @param {Object} req Cloud Function request context.
* @param {Object} res Cloud Function response context.
*/

// Include JSON data
/* Another failed attempt! "jQuery" and "$" both traced back undefined on deploy in Cloud Functions.
$.getJSON('github.com/mUtterberg/CareeerAction/blob/master/careers.json').done(function (data) {
  careers = data;
  careerToday = careers[Math.floor(Math.random() * careers.length)];
})
*/

/*// Pick random career title
function pickRandomCareer(){
        window.selectedCareer = window.careers[Math.floor(Math.random() * window.careers.length)];
        console.log(window.selectedCareer);
        console.log(window.careers);
    }

// Define a career of the day
var careerToday = pickRandomCareer()*/

var careerToday = "GOING TO BE AWESOME.";

const careers = [
  "Accountants and Auditors",
  "Actors",
  "Actuaries",
  "Administrative Services Managers",
  "Adult Literacy and High School Equivalency Diploma Teachers",
  "Advertising, Promotions, and Marketing Managers",
  "Advertising Sales Agents",
  "Aerospace Engineering and Operations Technicians",
  "Aerospace Engineers",
  "Agricultural and Food Science Technicians",
  "Agricultural and Food Scientists",
  "Agricultural Engineers",
  "Agricultural Workers",
  "Aircraft and Avionics Equipment Mechanics and Technicians",
  "Airline and Commercial Pilots",
  "Air Traffic Controllers",
  "Animal Care and Service Workers",
  "Announcers",
  "Anthropologists and Archeologists",
  "Appraisers and Assessors of Real Estate",
  "Arbitrators, Mediators, and Conciliators",
  "Architects",
  "Architectural and Engineering Managers",
  "Archivists, Curators, and Museum Workers",
  "Art Directors",
  "Assemblers and Fabricators",
  "Athletes and Sports Competitors",
  "Athletic Trainers",
  "Atmospheric Scientists, Including Meteorologists",
  "Audiologists",
  "Automotive Body and Glass Repairers",
  "Automotive Service Technicians and Mechanics",
  "Bakers",
  "Barbers, Hairstylists, and Cosmetologists",
  "Bartenders",
  "Bill and Account Collectors",
  "Biochemists and Biophysicists",
  "Biological Technicians",
  "Biomedical Engineers",
  "Boilermakers",
  "Bookkeeping, Accounting, and Auditing Clerks",
  "Broadcast and Sound Engineering Technicians",
  "Budget Analysts",
  "Bus Drivers",
  "Butchers",
  "Career and Technical Education Teachers",
  "Carpenters",
  "Cartographers and Photogrammetrists",
  "Cashiers",
  "Chefs and Head Cooks",
  "Chemical Engineers",
  "Chemical Technicians",
  "Chemists and Materials Scientists",
  "Childcare Workers",
  "Chiropractors",
  "Civil Engineering Technicians",
  "Civil Engineers",
  "Claims Adjusters, Appraisers, Examiners, and Investigators",
  "Coaches and Scouts",
  "Compensation, Benefits, and Job Analysis Specialists",
  "Compensation and Benefits Managers",
  "Computer and Information Research Scientists",
  "Computer and Information Systems Managers",
  "Computer Hardware Engineers",
  "Computer Network Architects",
  "Computer Programmers",
  "Computer Support Specialists",
  "Computer Systems Analysts",
  "Conservation Scientists and Foresters",
  "Construction and Building Inspectors",
  "Construction Equipment Operators",
  "Construction Laborers and Helpers",
  "Construction Managers",
  "Cooks",
  "Correctional Officers and Bailiffs",
  "Cost Estimators",
  "Court Reporters",
  "Craft and Fine Artists",
  "Customer Service Representatives",
  "Dancers and Choreographers",
  "Database Administrators",
  "Delivery Truck Drivers and Driver/Sales Workers",
  "Dental and Ophthalmic Laboratory Technicians and Medical Appliance Technicians",
  "Dental Assistants",
  "Dental Hygienists",
  "Dentists",
  "Desktop Publishers",
  "Diagnostic Medical Sonographers and Cardiovascular Technologists and Technicians, Including Vascular Technologists",
  "Diesel Service Technicians and Mechanics",
  "Dietitians and Nutritionists",
  "Drafters",
  "Drywall and Ceiling Tile Installers, and Tapers",
  "Economists",
  "Editors",
  "Electrical and Electronics Engineering Technicians",
  "Electrical and Electronics Engineers",
  "Electrical and Electronics Installers and Repairers",
  "Electricians",
  "Electro-mechanical Technicians",
  "Elementary, Middle, and High School Principals",
  "Elevator Installers and Repairers",
  "Emergency Management Directors",
  "EMTs and Paramedics",
  "Environmental Engineering Technicians",
  "Environmental Engineers",
  "Environmental Science and Protection Technicians",
  "Environmental Scientists and Specialists",
  "Epidemiologists",
  "Exercise Physiologists",
  "Farmers, Ranchers, and Other Agricultural Managers",
  "Fashion Designers",
  "Film and Video Editors and Camera Operators",
  "Financial Analysts",
  "Financial Clerks",
  "Financial Examiners",
  "Financial Managers",
  "Firefighters",
  "Fire Inspectors",
  "Fishing and Hunting Workers",
  "Fitness Trainers and Instructors",
  "Flight Attendants",
  "Flooring Installers and Tile and Marble Setters",
  "Floral Designers",
  "Food and Beverage Serving and Related Workers",
  "Food and Tobacco Processing Workers",
  "Food Preparation Workers",
  "Food Service Managers",
  "Forensic Science Technicians",
  "Forest and Conservation Workers",
  "Fundraisers",
  "Funeral Service Workers",
  "Gaming Services Workers",
  "General Maintenance and Repair Workers",
  "General Office Clerks",
  "Genetic Counselors",
  "Geographers",
  "Geological and Petroleum Technicians",
  "Geoscientists",
  "Glaziers",
  "Graphic Designers",
  "Grounds Maintenance Workers",
  "Hand Laborers and Material Movers",
  "Hazardous Materials Removal Workers",
  "Health and Safety Engineers",
  "Health Educators and Community Health Workers",
  "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
  "Heavy and Tractor-trailer Truck Drivers",
  "Heavy Vehicle and Mobile Equipment Service Technicians",
  "High School Teachers",
  "Historians",
  "Home Health Aides and Personal Care Aides",
  "Human Resources Managers",
  "Human Resources Specialists",
  "Hydrologists",
  "Industrial Designers",
  "Industrial Engineering Technicians",
  "Industrial Engineers",
  "Industrial Machinery Mechanics, Machinery Maintenance Workers, and Millwrights",
  "Industrial Production Managers",
  "Information Clerks",
  "Information Security Analysts",
  "Instructional Coordinators",
  "Insulation Workers",
  "Insurance Sales Agents",
  "Insurance Underwriters",
  "Interior Designers",
  "Interpreters and Translators",
  "Ironworkers",
  "Janitors and Building Cleaners",
  "Jewelers and Precious Stone and Metal Workers",
  "Judges and Hearing Officers",
  "Kindergarten and Elementary School Teachers",
  "Labor Relations Specialists",
  "Landscape Architects",
  "Lawyers",
  "Librarians",
  "Library Technicians and Assistants",
  "Licensed Practical and Licensed Vocational Nurses",
  "Line Installers and Repairers",
  "Loan Officers",
  "Lodging Managers",
  "Logging Workers",
  "Logisticians",
  "Machinists and Tool and Die Makers",
  "Management Analysts",
  "Manicurists and Pedicurists",
  "Marine Engineers and Naval Architects",
  "Market Research Analysts",
  "Marriage and Family Therapists",
  "Masonry Workers",
  "Massage Therapists",
  "Material Moving Machine Operators",
  "Material Recording Clerks",
  "Materials Engineers",
  "Mathematicians and Statisticians",
  "Mechanical Engineering Technicians",
  "Mechanical Engineers",
  "Medical and Clinical Laboratory Technologists and Technicians",
  "Medical and Health Services Managers",
  "Medical Assistants",
  "Medical Equipment Repairers",
  "Medical Records and Health Information Technicians",
  "Medical Scientists",
  "Medical Transcriptionists",
  "Meeting, Convention, and Event Planners",
  "Metal and Plastic Machine Workers",
  "Microbiologists",
  "Middle School Teachers",
  "Military Careers",
  "Mining and Geological Engineers",
  "Models",
  "Multimedia Artists and Animators",
  "Music Directors and Composers",
  "Musicians and Singers",
  "Natural Sciences Managers",
  "Network and Computer Systems Administrators",
  "Nuclear Engineers",
  "Nuclear Medicine Technologists",
  "Nuclear Technicians",
  "Nurse Anesthetists, Nurse Midwives, and Nurse Practitioners",
  "Nursing Assistants and Orderlies",
  "Occupational Health and Safety Specialists and Technicians",
  "Occupational Therapists",
  "Occupational Therapy Assistants and Aides",
  "Operations Research Analysts",
  "Opticians",
  "Optometrists",
  "Orthotists and Prosthetists",
  "Painters, Construction and Maintenance",
  "Painting and Coating Workers",
  "Paralegals and Legal Assistants",
  "Personal Financial Advisors",
  "Pest Control Workers",
  "Petroleum Engineers",
  "Pharmacists",
  "Pharmacy Technicians",
  "Phlebotomists",
  "Photographers",
  "Physical Therapist Assistants and Aides",
  "Physical Therapists",
  "Physician Assistants",
  "Physicians and Surgeons",
  "Physicists and Astronomers",
  "Plumbers, Pipefitters, and Steamfitters",
  "Podiatrists",
  "Police, Fire, and Ambulance Dispatchers",
  "Police and Detectives",
  "Political Scientists",
  "Postal Service Workers",
  "Postsecondary Education Administrators",
  "Postsecondary Teachers",
  "Power Plant Operators, Distributors, and Dispatchers",
  "Preschool and Childcare Center Directors",
  "Preschool Teachers",
  "Private Detectives and Investigators",
  "Probation Officers and Correctional Treatment Specialists",
  "Producers and Directors",
  "Property, Real Estate, and Community Association Managers",
  "Psychiatric Technicians and Aides",
  "Psychologists",
  "Public Relations and Fundraising Managers",
  "Public Relations Specialists",
  "Purchasing Managers, Buyers, and Purchasing Agents",
  "Quality Control Inspectors",
  "Radiation Therapists",
  "Radiologic and MRI Technologists",
  "Railroad Workers",
  "Real Estate Brokers and Sales Agents",
  "Receptionists",
  "Recreational Therapists",
  "Recreation Workers",
  "Registered Nurses",
  "Rehabilitation Counselors",
  "Reporters, Correspondents, and Broadcast News Analysts",
  "Respiratory Therapists",
  "Retail Sales Workers",
  "Roofers",
  "Sales Engineers",
  "Sales Managers",
  "School and Career Counselors",
  "Secretaries and Administrative Assistants",
  "Securities, Commodities, and Financial Services Sales Agents",
  "Security Guards and Gaming Surveillance Officers",
  "Sheet Metal Workers",
  "Skincare Specialists",
  "Small Engine Mechanics",
  "Social and Community Service Managers",
  "Social and Human Service Assistants",
  "Social Workers",
  "Sociologists",
  "Software Developers",
  "Solar Photovoltaic Installers",
  "Special Education Teachers",
  "Speech-Language Pathologists",
  "Stationary Engineers and Boiler Operators",
  "Substance Abuse, Behavioral Disorder, and Mental Health Counselors",
  "Surgical Technologists",
  "Surveying and Mapping Technicians",
  "Surveyors",
  "Survey Researchers",
  "Tax Examiners and Collectors, and Revenue Agents",
  "Taxi Drivers, Ride-Hailing Drivers, and Chauffeurs",
  "Teacher Assistants",
  "Technical Writers",
  "Telecommunications Equipment Installers and Repairers",
  "Tellers",
  "Top Executives",
  "Training and Development Managers",
  "Training and Development Specialists",
  "Travel Agents",
  "Umpires, Referees, and Other Sports Officials",
  "Urban and Regional Planners",
  "Veterinarians",
  "Veterinary Assistants and Laboratory Animal Caretakers",
  "Veterinary Technologists and Technicians",
  "Waiters and Waitresses",
  "Water and Wastewater Treatment Plant and System Operators",
  "Water Transportation Workers",
  "Web Developers",
  "Welders, Cutters, Solderers, and Brazers",
  "Wholesale and Manufacturing Sales Representatives",
  "Wind Turbine Technicians",
  "Woodworkers",
  "Writers and Authors",
  "Zoologists and Wildlife Biologists"
]

function randomCareer() {
        const factIndex = Math.floor(Math.random() * careers.length);
        careerToday = careers[factIndex];
    }

exports.helloHttp = function helloHttp (req, res) {
  response = "Today's career spotlight is " + careerToday //Default response from the webhook to show it's working


  res.setHeader('Content-Type', 'application/json'); //Requires application/json MIME type
  res.send(JSON.stringify({ "speech": response, "displayText": response
  //"speech" is the spoken version of the response, "displayText" is the visual version
  }));
};
